import type { ExportConfig, GeneratedFile } from '../types.js';
import { shCommentSafe } from '../sh.js';
import { dirName } from './common.js';

/**
 * Windows-Batchdatei, die den erzeugten Satz auf den Server bringt und dort
 * Zeilenenden, Rechte und Gruppe richtigstellt.
 *
 * Verwendet ausschliesslich Bordmittel: den OpenSSH-Client (seit Windows 10
 * Version 1809) und tar (seit 1803).
 *
 * Standardweg ist ein einziger Durchgang: tar schreibt den Satz in die
 * SSH-Verbindung, die Gegenseite entpackt und richtet ein. Das kostet genau
 * eine Passwortabfrage. Das sonst uebliche Wiederverwenden einer Verbindung
 * ueber ControlMaster gibt es im OpenSSH fuer Windows nicht.
 */
export function generateDeployScript(
  config: ExportConfig,
  files: readonly GeneratedFile[],
): GeneratedFile {
  const targetDir = dirName(config.scriptPath);

  // Nur was auf den Server gehoert: die Skripte und die Anleitung. Die
  // Windows-Helfer bleiben hier.
  const transfer = files
    .filter((file) => file.name.endsWith('.sh') || file.name.endsWith('.md'))
    .map((file) => file.name);

  // Wird auf der Gegenseite in einer Zeile ausgefuehrt.
  const remoteSetup = [
    `sed -i 's/\\r$//' *.sh`,
    'chmod 750 *.sh',
    'chgrp %TARGET_GROUP% *.sh 2>/dev/null',
  ].join(' && ');

  const lines = [
    '@echo off',
    'setlocal enabledelayedexpansion',
    '',
    'rem ============================================================',
    'rem  Dateien auf den HANA-Server uebertragen',
    'rem',
    `rem  Kunde : ${shCommentSafe(config.customer) || '-'}`,
    `rem  Ziel  : ${config.osUser}@${config.host}:${targetDir}`,
    'rem',
    'rem  Nutzt nur Windows-Bordmittel: den OpenSSH-Client (ab Windows 10',
    'rem  Version 1809) und tar (ab 1803).',
    'rem',
    'rem  Aufruf:',
    'rem    00_dateien_uebertragen.cmd         uebertragen, eine Passwortabfrage',
    'rem    00_dateien_uebertragen.cmd --key   einmalig SSH-Schluessel einrichten,',
    'rem                                       danach gar keine Abfrage mehr',
    'rem    00_dateien_uebertragen.cmd --scp   Einzelschritte statt einem Durchgang',
    'rem',
    'rem  Diese Datei muss im selben Ordner liegen wie die Skripte.',
    'rem',
    'rem  Generiert durch HANAScriptGenerator.',
    'rem ============================================================',
    '',
    'rem --- Konfiguration ------------------------------------------',
    '',
    `set "SSH_HOST=${config.host}"`,
    `set "SSH_USER=${config.osUser}"`,
    'set "SSH_PORT=22"',
    `set "TARGET_DIR=${targetDir}"`,
    'set "TARGET_GROUP=sapsys"',
    'set "SSH_KEY=%USERPROFILE%\\.ssh\\id_ed25519"',
    '',
    `set "FILES=${transfer.join(' ')}"`,
    '',
    'rem --- OpenSSH vorhanden? -------------------------------------',
    '',
    'where ssh >nul 2>&1',
    'if errorlevel 1 goto :no_openssh',
    'where scp >nul 2>&1',
    'if errorlevel 1 goto :no_openssh',
    '',
    'if /I "%~1"=="--key" goto :setup_key',
    '',
    'rem --- Liegen alle Dateien hier? ------------------------------',
    '',
    'pushd "%~dp0"',
    '',
    'set "MISSING="',
    'for %%F in (%FILES%) do if not exist "%%F" (',
    '    echo FEHLER: Datei fehlt in diesem Ordner: %%F',
    '    set "MISSING=1"',
    ')',
    'if defined MISSING goto :missing',
    '',
    'echo Ziel: %SSH_USER%@%SSH_HOST%:%TARGET_DIR%',
    'echo.',
    'echo Uebertragen werden:',
    'for %%F in (%FILES%) do echo   %%F',
    'echo.',
    '',
    'rem Ist ein Schluessel hinterlegt, entfaellt die Abfrage ganz.',
    'ssh -o BatchMode=yes -o ConnectTimeout=10 -p %SSH_PORT% %SSH_USER%@%SSH_HOST% "exit" >nul 2>&1',
    'if errorlevel 1 (',
    '    echo Das Passwort von %SSH_USER% wird einmal abgefragt.',
    '    echo.',
    '    echo Wer es gar nicht mehr eingeben will, richtet einmalig einen',
    '    echo SSH-Schluessel ein:',
    '    echo     %~nx0 --key',
    ') else (',
    '    echo SSH-Schluessel erkannt, es wird kein Passwort abgefragt.',
    ')',
    'echo.',
    '',
    'if /I "%~1"=="--scp" goto :use_scp',
    '',
    'rem --- Ein Durchgang ueber tar --------------------------------',
    'rem',
    'rem  tar schreibt den Satz in die SSH-Verbindung, die Gegenseite',
    'rem  entpackt ihn und setzt gleich Zeilenenden, Rechte und Gruppe.',
    'rem  Eine Verbindung, eine Abfrage. Das Passwort liest ssh von der',
    'rem  Konsole und nicht aus der Pipe, deshalb stoert das Umleiten nicht.',
    '',
    'where tar >nul 2>&1',
    'if errorlevel 1 (',
    '    echo Hinweis: tar wurde nicht gefunden, es wird einzeln uebertragen.',
    '    echo.',
    '    goto :use_scp',
    ')',
    '',
    'echo Uebertrage in einem Durchgang ...',
    `tar -cf - %FILES% | ssh -p %SSH_PORT% %SSH_USER%@%SSH_HOST% "mkdir -p '%TARGET_DIR%' && cd '%TARGET_DIR%' && tar -xf - && ${remoteSetup}; ls -l *.sh"`,
    'if errorlevel 1 goto :transfer_failed',
    'goto :done',
    '',
    'rem --- Einzelschritte -----------------------------------------',
    'rem',
    'rem  Rueckfallweg ohne tar: drei Verbindungen, also drei Abfragen.',
    '',
    ':use_scp',
    'echo [1/3] Lege %TARGET_DIR% an ...',
    'ssh -p %SSH_PORT% %SSH_USER%@%SSH_HOST% "mkdir -p \'%TARGET_DIR%\'"',
    'if errorlevel 1 goto :transfer_failed',
    '',
    'echo [2/3] Uebertrage Dateien ...',
    'scp -P %SSH_PORT% %FILES% %SSH_USER%@%SSH_HOST%:%TARGET_DIR%/',
    'if errorlevel 1 goto :transfer_failed',
    '',
    'echo [3/3] Setze Zeilenenden, Rechte und Gruppe ...',
    `ssh -p %SSH_PORT% %SSH_USER%@%SSH_HOST% "cd '%TARGET_DIR%' && ${remoteSetup}; ls -l *.sh"`,
    'if errorlevel 1 goto :transfer_failed',
    '',
    'rem --- Fertig -------------------------------------------------',
    'rem',
    'rem  chown fehlt mit Absicht: den Eigentuemer darf nur root aendern.',
    'rem  Noetig ist es auch nicht, denn was als %SSH_USER% ankommt, gehoert',
    'rem  bereits %SSH_USER%. Die Gruppe laesst sich mit chgrp setzen, weil',
    'rem  der Benutzer ihr angehoert.',
    '',
    ':done',
    'popd',
    '',
    'echo.',
    'echo ============================================================',
    'echo Uebertragung abgeschlossen.',
    'echo.',
    'echo Weiter auf dem Server:',
    'echo   ssh %SSH_USER%@%SSH_HOST%',
    'echo   cd %TARGET_DIR%',
    'echo   ./01_setup_userstore.sh',
    'echo   ./02_prepare_dirs.sh',
    'echo   ./03_preflight.sh',
    'echo ============================================================',
    'echo.',
    'pause',
    'exit /b 0',
    '',
    'rem --- SSH-Schluessel einrichten ------------------------------',
    'rem',
    'rem  Einmal das Passwort, danach nie wieder. Nur der oeffentliche Teil',
    'rem  des Schluessels geht an ~/.ssh/authorized_keys des Servers; der',
    'rem  private Teil verlaesst diesen Rechner nicht.',
    '',
    ':setup_key',
    'echo Richte SSH-Schluessel fuer %SSH_USER%@%SSH_HOST% ein.',
    'echo.',
    '',
    'where ssh-keygen >nul 2>&1',
    'if errorlevel 1 goto :no_openssh',
    '',
    'if exist "%SSH_KEY%" (',
    '    echo Vorhandener Schluessel wird verwendet: %SSH_KEY%',
    ') else (',
    '    echo Erzeuge neuen Schluessel: %SSH_KEY%',
    '    if not exist "%USERPROFILE%\\.ssh" mkdir "%USERPROFILE%\\.ssh"',
    '    ssh-keygen -t ed25519 -N "" -C "HANAScriptGenerator" -f "%SSH_KEY%"',
    '    if errorlevel 1 goto :key_failed',
    ')',
    'echo.',
    '',
    'if not exist "%SSH_KEY%.pub" goto :key_failed',
    '',
    'echo Das Passwort von %SSH_USER% wird jetzt ein letztes Mal gebraucht.',
    'echo.',
    'type "%SSH_KEY%.pub" | ssh -p %SSH_PORT% %SSH_USER%@%SSH_HOST% "umask 077; mkdir -p ~/.ssh; cat >> ~/.ssh/authorized_keys; sort -u ~/.ssh/authorized_keys -o ~/.ssh/authorized_keys"',
    'if errorlevel 1 goto :key_failed',
    '',
    'echo.',
    'echo Teste die Anmeldung ohne Passwort ...',
    'ssh -o BatchMode=yes -o ConnectTimeout=10 -p %SSH_PORT% %SSH_USER%@%SSH_HOST% "echo Anmeldung ohne Passwort funktioniert."',
    'if errorlevel 1 (',
    '    echo.',
    '    echo WARNUNG: Der Test ist fehlgeschlagen.',
    '    echo Manche Server verbieten die Schluesselanmeldung oder verlangen',
    '    echo strengere Rechte. Auf dem Server als %SSH_USER% pruefen:',
    '    echo   chmod 700 ~/.ssh',
    '    echo   chmod 600 ~/.ssh/authorized_keys',
    '    echo.',
    '    pause',
    '    exit /b 1',
    ')',
    '',
    'echo.',
    'echo Fertig. Jetzt ohne Schalter starten, es wird kein Passwort mehr',
    'echo abgefragt:',
    'echo   %~nx0',
    'echo.',
    'pause',
    'exit /b 0',
    '',
    'rem --- Fehlerfaelle -------------------------------------------',
    '',
    ':no_openssh',
    'echo FEHLER: ssh, scp oder ssh-keygen wurde nicht gefunden.',
    'echo.',
    'echo Der OpenSSH-Client ist ein Windows-Bordmittel, aber nicht auf',
    'echo jedem System eingeschaltet. Einschalten unter:',
    'echo   Einstellungen - Apps - Optionale Features - OpenSSH-Client',
    'echo.',
    'echo Oder in einer PowerShell als Administrator:',
    'echo   Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0',
    'echo.',
    'pause',
    'exit /b 1',
    '',
    ':missing',
    'popd',
    'echo.',
    'echo Diese Datei muss im selben Ordner liegen wie die erzeugten',
    'echo Skripte. Das ZIP also vollstaendig entpacken und erst dann',
    'echo starten.',
    'echo.',
    'pause',
    'exit /b 1',
    '',
    ':transfer_failed',
    'popd',
    'echo.',
    'echo FEHLER: Die Uebertragung ist fehlgeschlagen.',
    'echo Zu pruefen:',
    'echo   - Ist %SSH_HOST% ueber SSH erreichbar? Test: ssh %SSH_USER%@%SSH_HOST%',
    'echo   - Stimmt der Benutzer %SSH_USER%?',
    'echo   - Darf %SSH_USER% in %TARGET_DIR% schreiben?',
    'echo.',
    'echo Mit %~nx0 --scp laufen die Schritte einzeln, das zeigt genauer,',
    'echo woran es scheitert.',
    'echo.',
    'pause',
    'exit /b 1',
    '',
    ':key_failed',
    'echo.',
    'echo FEHLER: Der Schluessel konnte nicht eingerichtet werden.',
    'echo Die Meldung darueber sagt, woran es lag.',
    'echo.',
    'pause',
    'exit /b 1',
    '',
  ];

  return {
    name: '00_dateien_uebertragen.cmd',
    title: '0 · Übertragen',
    purpose: `Überträgt die Skripte nach ${config.osUser}@${config.host}:${targetDir} und setzt Zeilenenden, Rechte und Gruppe – in einem Durchgang mit einer Passwortabfrage, mit --key ganz ohne.`,
    language: 'batch',
    executable: false,
    // cmd.exe verschluckt sich an Batchdateien mit reinen LF-Zeilenenden.
    content: lines.join('\r\n'),
  };
}
