import type { ExportConfig, GeneratedFile } from '../types.js';
import { shCommentSafe } from '../sh.js';
import { dirName } from './common.js';

/**
 * Windows-Batchdatei, die den erzeugten Satz per scp auf den Server bringt
 * und dort Zeilenenden, Rechte und Gruppe richtigstellt.
 *
 * Verwendet ausschliesslich Bordmittel: den OpenSSH-Client, der seit
 * Windows 10 1809 zu Windows gehoert.
 */
export function generateDeployScript(
  config: ExportConfig,
  files: readonly GeneratedFile[],
): GeneratedFile {
  const targetDir = dirName(config.scriptPath);

  // Nur was auf den Server gehoert: die Skripte und die Anleitung. Die
  // Windows-Helfer bleiben hier.
  const transfer = files
    .filter((file) => file.name.endsWith('.sh') || file.name.endsWith('.md'))
    .map((file) => file.name);

  const lines = [
    '@echo off',
    'setlocal enabledelayedexpansion',
    '',
    'rem ============================================================',
    'rem  Dateien auf den HANA-Server uebertragen',
    'rem',
    `rem  Kunde : ${shCommentSafe(config.customer) || '-'}`,
    `rem  Ziel  : ${config.osUser}@${config.host}:${targetDir}`,
    'rem',
    'rem  Nutzt scp und ssh aus dem OpenSSH-Client, der seit Windows 10',
    'rem  Version 1809 zu Windows gehoert. Keine Zusatzsoftware noetig.',
    'rem',
    'rem  Diese Datei muss im selben Ordner liegen wie die Skripte.',
    'rem',
    'rem  Generiert durch HANAScriptGenerator.',
    'rem ============================================================',
    '',
    'rem --- Konfiguration ------------------------------------------',
    '',
    `set "SSH_HOST=${config.host}"`,
    `set "SSH_USER=${config.osUser}"`,
    'set "SSH_PORT=22"',
    `set "TARGET_DIR=${targetDir}"`,
    'set "TARGET_GROUP=sapsys"',
    '',
    `set "FILES=${transfer.join(' ')}"`,
    '',
    'rem --- OpenSSH vorhanden? -------------------------------------',
    '',
    'where scp >nul 2>&1',
    'if errorlevel 1 goto :no_openssh',
    'where ssh >nul 2>&1',
    'if errorlevel 1 goto :no_openssh',
    '',
    'rem --- Liegen alle Dateien hier? ------------------------------',
    '',
    'pushd "%~dp0"',
    '',
    'set "MISSING="',
    'for %%F in (%FILES%) do if not exist "%%F" (',
    '    echo FEHLER: Datei fehlt in diesem Ordner: %%F',
    '    set "MISSING=1"',
    ')',
    'if defined MISSING goto :missing',
    '',
    'echo Ziel: %SSH_USER%@%SSH_HOST%:%TARGET_DIR%',
    'echo.',
    'echo Uebertragen werden:',
    'for %%F in (%FILES%) do echo   %%F',
    'echo.',
    'echo Das Passwort von %SSH_USER% wird dreimal abgefragt:',
    'echo   1. Zielverzeichnis anlegen',
    'echo   2. Dateien uebertragen',
    'echo   3. Zeilenenden, Rechte und Gruppe setzen',
    'echo.',
    'echo Wer das vermeiden will, hinterlegt einmalig einen SSH-Schluessel:',
    'echo   ssh-keygen -t ed25519',
    'echo   type %%USERPROFILE%%\\.ssh\\id_ed25519.pub ^| ssh %SSH_USER%@%SSH_HOST% "mkdir -p ~/.ssh ^&^& cat ^>^> ~/.ssh/authorized_keys"',
    'echo.',
    'pause',
    'echo.',
    '',
    'rem --- 1. Zielverzeichnis anlegen -----------------------------',
    '',
    'echo [1/3] Lege %TARGET_DIR% an ...',
    'ssh -p %SSH_PORT% %SSH_USER%@%SSH_HOST% "mkdir -p \'%TARGET_DIR%\'"',
    'if errorlevel 1 goto :ssh_failed',
    '',
    'rem --- 2. Dateien uebertragen ---------------------------------',
    '',
    'echo [2/3] Uebertrage Dateien ...',
    'scp -P %SSH_PORT% %FILES% %SSH_USER%@%SSH_HOST%:%TARGET_DIR%/',
    'if errorlevel 1 goto :scp_failed',
    '',
    'rem --- 3. Zeilenenden, Rechte, Gruppe -------------------------',
    'rem',
    'rem  chown fehlt hier mit Absicht: den Eigentuemer darf nur root',
    'rem  aendern. Noetig ist es auch nicht, denn per scp als %SSH_USER%',
    'rem  uebertragene Dateien gehoeren bereits %SSH_USER%. Die Gruppe',
    'rem  laesst sich mit chgrp setzen, weil der Benutzer ihr angehoert.',
    'rem',
    'rem  Das sed raeumt Windows-Zeilenenden weg, falls jemand eine Datei',
    'rem  zwischendurch im Editor gespeichert hat.',
    '',
    'echo [3/3] Setze Zeilenenden, Rechte und Gruppe ...',
    'ssh -p %SSH_PORT% %SSH_USER%@%SSH_HOST% "cd \'%TARGET_DIR%\' && sed -i \'s/\\r$//\' *.sh && chmod 750 *.sh && chgrp %TARGET_GROUP% *.sh 2>/dev/null; ls -l *.sh"',
    'if errorlevel 1 goto :ssh_failed',
    '',
    'popd',
    '',
    'echo.',
    'echo ============================================================',
    'echo Uebertragung abgeschlossen.',
    'echo.',
    'echo Weiter auf dem Server:',
    'echo   ssh %SSH_USER%@%SSH_HOST%',
    'echo   cd %TARGET_DIR%',
    'echo   ./01_setup_userstore.sh',
    'echo   ./02_prepare_dirs.sh',
    'echo   ./03_preflight.sh',
    'echo ============================================================',
    'echo.',
    'pause',
    'exit /b 0',
    '',
    'rem --- Fehlerfaelle -------------------------------------------',
    '',
    ':no_openssh',
    'echo FEHLER: ssh oder scp wurde nicht gefunden.',
    'echo.',
    'echo Der OpenSSH-Client ist ein Windows-Bordmittel, aber nicht auf',
    'echo jedem System eingeschaltet. Einschalten unter:',
    'echo   Einstellungen - Apps - Optionale Features - OpenSSH-Client',
    'echo.',
    'echo Oder in einer PowerShell als Administrator:',
    'echo   Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0',
    'echo.',
    'pause',
    'exit /b 1',
    '',
    ':missing',
    'popd',
    'echo.',
    'echo Diese Datei muss im selben Ordner liegen wie die erzeugten',
    'echo Skripte. Das ZIP also vollstaendig entpacken und erst dann',
    'echo starten.',
    'echo.',
    'pause',
    'exit /b 1',
    '',
    ':scp_failed',
    'popd',
    'echo.',
    'echo FEHLER: Die Uebertragung ist fehlgeschlagen.',
    'echo Zu pruefen:',
    'echo   - Ist %SSH_HOST% ueber SSH erreichbar? Test: ssh %SSH_USER%@%SSH_HOST%',
    'echo   - Stimmt der Benutzer %SSH_USER%?',
    'echo   - Darf %SSH_USER% in %TARGET_DIR% schreiben?',
    'echo.',
    'pause',
    'exit /b 1',
    '',
    ':ssh_failed',
    'popd',
    'echo.',
    'echo FEHLER: Ein Befehl auf dem Server ist fehlgeschlagen.',
    'echo Die Meldung darueber sagt, woran es lag.',
    'echo.',
    'pause',
    'exit /b 1',
    '',
  ];

  return {
    name: '00_dateien_uebertragen.cmd',
    title: '0 · Übertragen',
    purpose: `Kopiert die Skripte per scp nach ${config.osUser}@${config.host}:${targetDir} und setzt dort Zeilenenden, Rechte und Gruppe.`,
    language: 'batch',
    executable: false,
    // cmd.exe verschluckt sich an Batchdateien mit reinen LF-Zeilenenden.
    content: lines.join('\r\n'),
  };
}
